[package]
name = "MVSync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.8"
futures = "0.3.28"
futures-timer = "3.0.2"
mvutils = { path = "../MVUtils" }
