[package]
name = "mvsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
debug = false

[features]
all = ["command-buffers", "main-thread"]
command-buffers = []
main-thread = []

[dependencies]
crossbeam-channel = "0.5.8"
mvutils = { path = "../MVUtils" } #temporary: https://github.com/TeamMV/MVUtils
